# Generated by Django 2.2.2 on 2019-07-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True, verbose_name='عنوان')),
                ('url', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کالا')),
                ('price', models.TextField(blank=True, verbose_name='رنج قیمت ها')),
                ('amount', models.TextField(blank=True, verbose_name='میزان سفارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات سفارش')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کالا')),
                ('prices', models.TextField(blank=True, verbose_name='رنج قیمت ها')),
                ('order_ranges', models.TextField(blank=True, verbose_name='رنج سفارش')),
                ('max_order', models.CharField(blank=True, max_length=200, verbose_name='سقف سفارش')),
                ('deliver_at', models.DateField(null=True, verbose_name='تاریخ تحویل')),
                ('featured_image', models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='تصویر اصلی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
