# Generated by Django 2.2.2 on 2019-07-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': '3. تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': '2. سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': '1. محصولات'},
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(blank=True, max_length=200, verbose_name='میزان سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=200, verbose_name='قیمت'),
        ),
    ]
