# Generated by Django 2.2.2 on 2019-07-01 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_ranges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('order_range', models.TextField(verbose_name='رنج سفارش')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.TextField()),
                ('prices', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.price_ranges', verbose_name='رنج قیمت ها')),
            ],
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
