# Generated by Django 2.2.2 on 2019-07-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190706_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کالا')),
                ('price', models.CharField(blank=True, max_length=200, verbose_name='قیمت')),
                ('amount', models.CharField(blank=True, max_length=200, verbose_name='میزان سفارش')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': '4. سبدهای خرید',
            },
        ),
    ]
