# Generated by Django 2.2.2 on 2019-07-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190701_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.price_ranges', verbose_name='رنج قیمت ها'),
        ),
    ]
