# Generated by Django 2.2.2 on 2019-07-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190701_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prices',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(to='shop.price_ranges', verbose_name='رنج قیمت ها'),
        ),
    ]
