# Generated by Django 2.2.2 on 2019-07-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.TextField(blank=True, max_length=200, verbose_name='لیست میزان سفارشات'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.TextField(blank=True, max_length=200, verbose_name='لیست قیمت ها'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='title',
            field=models.TextField(max_length=200, verbose_name='لیست کالاهای سفارش'),
        ),
    ]
