# Generated by Django 2.2.2 on 2019-07-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190701_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price_ranges',
            options={'verbose_name': 'رنج قیمت', 'verbose_name_plural': 'رنج قیمت'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='prices',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.price_ranges', verbose_name='رنج قیمت ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(verbose_name='عنوان'),
        ),
    ]
