# Generated by Django 2.2.2 on 2019-07-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190702_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prices',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(null=True, to='shop.price_ranges', verbose_name='رنج قیمت ها'),
        ),
    ]
