# Generated by Django 2.2.2 on 2019-07-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190702_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(to='shop.price_ranges', verbose_name='رنج قیمت ها'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='shop.image', verbose_name='تصاویر'),
        ),
    ]
