# Generated by Django 2.2.2 on 2019-07-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190702_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='shop.image', verbose_name='گالری تصاویر'),
        ),
    ]
