# Generated by Django 2.2.2 on 2019-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190706_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ordered_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='سفارش های ثبت شده'),
        ),
    ]
