# Generated by Django 2.2.2 on 2019-07-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190706_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ordered_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='سفارش های ثبت شده'),
        ),
    ]
