# Generated by Django 2.2.2 on 2019-07-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_max_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_order',
            field=models.CharField(blank=True, max_length=200, verbose_name='سقف سفارش'),
        ),
    ]
