# Generated by Django 2.2.2 on 2019-07-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190702_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deliver_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
