# Generated by Django 2.2.2 on 2019-07-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_deliver_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deliver_at',
            field=models.DateTimeField(null=True, verbose_name='تاریخ تحویل'),
        ),
    ]
