# Generated by Django 2.2.2 on 2019-07-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20190710_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete='models.CASCADE', to='shop.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(max_length=200, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=200, verbose_name='لیست عنوان کالاها'),
        ),
    ]
