# Generated by Django 2.2.2 on 2019-07-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20190702_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='gallery',
        ),
    ]
