# Generated by Django 2.2.2 on 2019-07-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20190710_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=200, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='تلفن'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=200, null=True, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=200, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete='models.CASCADE', to='shop.customer', verbose_name='نام مشتری'),
        ),
    ]
