# Generated by Django 2.2.2 on 2019-07-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20190704_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_ranges',
            name='price',
            field=models.CharField(blank=True, max_length=50, verbose_name='قیمت'),
        ),
    ]
