# Generated by Django 2.2.2 on 2019-07-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20190710_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(max_length=200, null=True, verbose_name='روش پرداخت'),
        ),
    ]
