# Generated by Django 2.2.2 on 2019-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20190704_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_ranges',
            field=models.TextField(blank=True, verbose_name='رنج سفارش'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='prices',
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.TextField(blank=True, verbose_name='رنج قیمت ها'),
        ),
    ]
