# Generated by Django 2.2.2 on 2019-07-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20190704_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کالا')),
                ('price', models.TextField(blank=True, verbose_name='رنج قیمت ها')),
                ('amount', models.TextField(blank=True, verbose_name='میزان سفارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات سفارش')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.DeleteModel(
            name='price_ranges',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان کالا'),
        ),
    ]
