# Generated by Django 2.2.2 on 2019-07-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20190710_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='title',
            field=models.TextField(max_length=200, verbose_name='لیست کالاها'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.TextField(blank=True, max_length=200, verbose_name='لیست میزان سفارشات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('free', 'ارسال رایگان'), ('tipax', 'تیپاکس'), ('post', 'پست'), ('fast-courier', 'پیک فوری')], max_length=200, null=True, verbose_name='روش ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', to='shop.customer', verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('online', 'درگاه اینترنتی بانک ملت'), ('cart-cart', 'کارت به کارت'), ('balance', 'استفاده از اعتبار حساب')], max_length=200, null=True, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.TextField(blank=True, max_length=200, verbose_name='لیست قیمت ها'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.TextField(blank=True, verbose_name='لیست کالاها'),
        ),
    ]
