# Generated by Django 2.2.2 on 2019-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20190711_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.CharField(choices=[('paid', 'پرداخت شده'), ('notpaid', 'پرداخت نشده')], max_length=200, null=True, verbose_name='وضعیت پرداخت'),
        ),
    ]
