# Generated by Django 2.2.2 on 2019-07-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('proccessing', 'درحال بررسی'), ('complete', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='proccessing', max_length=200, null=True, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('free', 'ارسال رایگان'), ('tipax', 'تیپاکس'), ('post', 'پست'), ('fast-courier', 'پیک فوری')], default='post', max_length=200, null=True, verbose_name='روش ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.CharField(blank=True, choices=[('paid', 'پرداخت شده'), ('notpaid', 'پرداخت نشده')], default='notpaid', max_length=200, null=True, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('online', 'درگاه اینترنتی بانک ملت'), ('cart-cart', 'کارت به کارت'), ('balance', 'استفاده از اعتبار حساب')], default='online', max_length=200, null=True, verbose_name='روش پرداخت'),
        ),
    ]
