# Generated by Django 2.2.2 on 2019-07-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20190712_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='قیمت پایه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_ranges',
            field=models.TextField(blank=True, verbose_name='محدوده سفارش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prices',
            field=models.TextField(blank=True, verbose_name='محدوده قیمت ها'),
        ),
    ]
