# Generated by Django 2.2.2 on 2019-07-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20190712_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(blank=True, max_length=200, null=True, verbose_name='قیمت پایه'),
        ),
    ]
