# Generated by Django 2.2.2 on 2019-07-15 10:40

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20190713_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='تصویر اصلی'),
        ),
    ]
