# Generated by Django 2.2.2 on 2019-07-15 13:40

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20190713_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Image'),
        ),
    ]
